name: Security Checks
on: [push]

jobs:
  test:
    name: OWASP ZAP SCANS
    runs-on: ubuntu-latest

    steps:
       - uses: actions/checkout@v2
         with:
          ref: master
       - name: Building Docker NodeGoat Image
         run: docker-compose build
       - name: Launching the app
         run: docker-compose up --detach

       - name: OWASP ZAP
         uses: zaproxy/action-baseline@v0.9.0
         with:
           # Target URL
           token: ${{ secrets.GITHUBTOKEN }}
           target: "http://localhost:4000"
           fail_action: false
           issue_title: Security Tests
